/** @type {import('tailwindcss').Config} */
// Tokens copied verbatim from dara-front/tailwind.config.js + globals.css so this
// standalone slice renders in the real LoudEcho V2 design language. Do not invent
// new colors here — extend dara-front instead when merging.
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-theme-light-surface-0": "#fff",
        "outline-theme-light-low-em": "#ececed",
        "text-theme-light-low-em": "#8d8a95",
        "text-theme-light-high-em": "#110c22",
        "text-theme-light-med-em": "#4f4b5c",
        "surface-theme-light-secondary-accent-1": "#e9ffea",
        "text-theme-light-success-on-accentlight": "#0a9c55",
        "color-transparent": "rgba(255, 255, 255, 0)",
        "color-primary-50": "#f1eeff",
        "text-theme-light-primary-on-accentlight": "#6347f4",
        "surface-theme-light-surface-1": "#f8f8f8",
        gainsboro: { 100: "#e6e6e6", 200: "#dedede" },
        lightgray: "#d4d4d4",
        whitesmoke: "#f1f1f2",
        "color-info-75": "#c2e2ff",
        "color-info-25": "#f5faff",
        brand: "#0a89c5",
        "surface-theme-light-surface-2": "#f3f3f4",
        "color-gray-100": "#e2e2e4",
        "color-primary-500": "#7357ff",
        "text-theme-light-disabled": "#b3b1b8",
        "color-info-50": "#e9f4ff",
        "color-light-light": "#fcfcfd",
        dimgray: "rgba(79, 75, 92, 0.8)",
        "neutral-900": "#0f172a",
        "neutral-500": "#64748b",
        cornflowerblue: { 100: "#45a6ff", 200: "#2b8ce6" },
        "color-gray-alpha-50": "rgba(17, 12, 34, 0.05)",
        "color-primary-25": "#f9f8ff",
        "outline-theme-light-primary-low-em": "#e2dcff",
        firebrick: "#cf2a2a",
        chocolate: "#d07d00",
        mediumseagreen: "#0a9c55",
        "text-theme-light-success-on-base": "#0baa60",
        lightskyblue: "#a0d2ff",
        "outline-theme-light-high-em": "#c6c5ca",
        gray: "#949196",
        "surface-theme-light-surface-high-em": "#2e293d",
        "text-theme-light-primary-on-base": "#7357ff",
        "text-theme-light-fail-on-base": "#cf2a2a",
        "surface-theme-light-success-accent-1": "#e2fcf0",
        "surface-theme-light-fail-accent-1": "#ffedf0",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        "accent-blue": "hsl(var(--accent-blue))",
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        geist: ["Geist", "ui-monospace", "monospace"],
      },
      borderRadius: {
        xl: "20px",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "sheet-in": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
      },
      animation: {
        shimmer: "shimmer 2s infinite",
        "sheet-in": "sheet-in 0.25s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
      },
    },
    fontSize: {
      base: "16px",
      xs: "12px",
      lg: "18px",
      "13xl": "32px",
      "7xl": "26px",
      lgi: "19px",
      "3xs": "10px",
      sm: "14px",
      "2xl": "21px",
      mid: "17px",
      xl: "20px",
      inherit: "inherit",
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
  },
  plugins: [],
};
